#!/usr/bin/perl
# ------------run------------------------------------------------------------------
# Shortcut script to run the kernel in either normal or debug mode.
# assumes $path is set to toolchain bin folder and $kern is set to the directory
# of the kernel source files.
use warnings;
use strict;

my $option = "";
my $runKernel = 1;
my $runUser = 0;
my $userComm = "";
my $userReload = 0;
my $userUpload = 0;
my $showHelp = 0;

# Parse commandline arguments.
if ($#ARGV > -1) {
  if ($ARGV[0] eq "debug") {
    $option = "-qemu -monitor telnet::4444,server -s";

  } elsif ($ARGV[0] eq "help") {
    $runKernel = 0;
    $showHelp = 1;

  } elsif ($ARGV[0] =~ /-[ur(ur)(ru)]/ && $#ARGV > 0) {
    if ($#ARGV > 1) {
      $userUpload = $ARGV[0] =~ /u/ || $ARGV[1] =~ /u/;
      $userReload = $ARGV[0] =~ /r/ || $ARGV[1] =~ /r/;
      $userComm = $ARGV[2];
      
    } else {
      $userComm = $ARGV[1];
      $userUpload = $ARGV[0] =~ /u/;
      $userReload = $ARGV[0] =~ /r/;
    }
    $runKernel = 0;
    $runUser = 1;

  } else {
    $runKernel = 0;
    $runUser = 1;
    $userComm = $ARGV[0];
  }
}

# Run the kernel.
if ($runKernel) {
  if (chdir $ENV{'KERN'} == 0) {
    print "Failed to change to android kernel directory.\n";
    exit -1;
  }
  system "emulator -avd ece353avd -kernel arch/arm/boot/zImage -show-kernel $option";
}

# Run the user program on the kernel.
# Assumes the given user program name $userComm is contained in
#   $KERN/../../$userComm
if ($runUser) {

  if (chdir "$ENV{'KERN'}/../../$userComm" == 0) {
    print "Failed to change to the $userComm directory.\n";
    exit -1;
  }

  if ($userReload) {
    system "adb kill-server";
    system "adb start-server";
  }

  # Test if adb is connected to the kernel.
  my $status = `adb devices`;
  if ($status =~ /\tdevice/) {

    # Reupload the user program if option was given.
    if ($userUpload) {
      `adb push $userComm /data/local`;
    }

    system "adb shell /data/local/$userComm";

  } else {
    print "adb is not ready yet. 
Execute \"run -r $userComm\" to restart the adb server.\n";
  }
    
}

if ($showHelp) {
  print <<END_;
Usage:  Run kernel:                         run     
        Run kernel in debug monitor:        run debug

        Run user programs: eg. ptree        run ptree
          option: -u upload executable      run -u ptree
          option: -r reload adb server      run -r ptree 
END_
}
