#!/bin/bash
# ------------run------------------------------------------------------------------
# Shortcut script to run the kernel in either normal or debug mode.
# assumes $path is set to toolchain bin folder and $kern is set to the directory
# of the kernel source files.

cd $KERN
if [ $? -ne 0 ]; then
  echo "failed to change to android kernel directory"
  exit
fi


if [ $# == 1 ] && [ $1 == "debug" ]; then
  emulator -avd ece353avd -kernel arch/arm/boot/zImage -show-kernel  -qemu -monitor telnet::4444,server -s
else
  if [ $# == 0 ]; then
    emulator -avd ece353avd -kernel arch/arm/boot/zImage -show-kernel
  else
    echo "Usage: run kernel normally:           run      "
    echo "       run kernel in debug monitor:   run debug"
  fi
fi
